spring:
  redis:
    host: 172.16.14.86
   # password: 
    database: 9
    port: 6379
    pool:
      max-idle: 20
      min-idle: 5
      max-active: 20
      max-wait: 3000
  freemarker:
    allow-request-override: false
    cache: true
    check-template-location: true
    charset: utf-8
    content-type: text/html
    expose-session-attributes: false
    expose-request-attributes: false
    expose-spring-macro-helpers: false
server:
  session:
    timeout: 1800
  max-http-header-size: 20971520
 # undertow:
    # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
   # io-threads: 4
    # 阻塞任务线程池, 当执行类似servlet请求阻塞操作, undertow会从这个线程池中取得线程,它的值设置取决于系统的负载，默认值为io-threads*8。
   # worker-threads: 20
eureka:
  client:
    service-url:
      defaultZone: http://172.16.20.112:1111/eureka/
  instance:
    hostname: DEV-FAQ-FRZ
    leaseExpirationDurationInSeconds: 30 # 续约到期时间（默认90秒） 表示多久没心跳将自己踢出
    prefer-ip-address: true
    ip-address: 172.16.12.12
    instance-id: ${eureka.instance.ip-address}:${spring.application.name}:${server.port}
  healthcheck:
    enabled: true # 开启健康检查（需要spring-boot-starter-actuator依赖）
logging:
  config: classpath:logback/logback.xml
  level:
    org:
      springframework: ERROR
      apache: ERROR
      hibernate: ERROR
      java:
        sql: debug
      com:
        softisland:
          middleware:
           domain:
             mapper: debug

tomcat:
  datasource:
    username: root
    password: Softisland1!
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.16.14.86:3306/middleware_service_test?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&autoReconnectForPools=true
    max-active: 50
    max-idle: 10
    min-idle: 1
    initial-size: 1
    validation-query: SELECT 1
    maxAge: 36000000
    validationInterval: 10
    testWhileIdle: true
    validationQueryTimeout: 1
    timeBetweenEvictionRunsMillis: 30000
    numTestsPerEvictionRun: 10






